name: PR Verification

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install shellcheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck

    - name: Run shellcheck on logger-txt
      run: shellcheck logger-txt

    - name: Run shellcheck on test suite
      run: shellcheck test-logger-txt.sh

    - name: Make scripts executable
      run: |
        chmod +x logger-txt
        chmod +x test-logger-txt.sh

    - name: Run test suite
      run: ./test-logger-txt.sh
